name: TestPlugin
version: ${project.version}
main: me.noaz.testplugin.TestPlugin
api-version: 1.13
author: noaz
description: A test plugin

commands:
  game:
    description: This command is regarding games.
    usage: /war join, /war leave
    aliases: [war]
    permission: TestPlugin.game
    permission-message: No access
  cg:
    description: Change current game and gamemode
    usage: /cg [map] [gamemode]
    aliases: [changeGame]
    permission: TestPlugin.admin
    permission-message: No access
  loadout:
    description: Opens the loadout selection menu
    usage: /loadout, /lo
    aliases: [lo]
    permission: TestPlugin.game
    permission-message: No access
  maps:
    description: List all playable maps
    usage: /maps
    permission: TestPlugin.admin
    permission-message: No access
  update:
    description: Allows to update various database information such as map creator and guns.
    usage: /update map [text], /update gun [gun name] [field to update] [data]
    permission: TestPlugin.admin
    permission-message: No access
  gun:
    description: Adds, deletes or saves a gun.
    usage: /gun [save, delete, add] [gun name]
    permisson: TestPlugin.admin
    permission-message: No access
  profile:
    descrtion: Displays a players stats
    usage: /profile [username]
    permission: TestPlugin.profile
    permission-message: No access
  ping:
    description: Displays ping - Connection time between client and server
    usage: /ping
    permission: TestPlugin.ping
    permission-message: No access
  resource:
    description: Changes the players resourcepack
    usage: /resource [2D, 3D]
    permission: TestPlugin.game
    permission-message: No access

permissions:
  TestPlugin.game:
    description: Allows to join and leave games
    default: true
  TestPlugin.admin:
    description: Grants access to all administrative commands
    default: op
  TestPlugin.profile:
    description: Allows to check another players profile
    default: true
  TestPlugin.ping:
    description: Allows player to ping himself
    default: true