name: TestPlugin
version: ${project.version}
main: me.noaz.testplugin.TestPlugin
api-version: 1.13
author: noaz
description: A test plugin

commands:
  game:
    aliases: [war]
    permission: TestPlugin.game
    description: This command is regarding games.
  cg:
    aliases: [changeGame]
    permission: TestPlugin.admin
    description: Change current game and gamemode
  maps:
    permission: TestPlugin.admin
    description: List all playable maps
  update:
    permission: TestPlugin.admin
    description: Allows to update various database information such as map creator and guns.
  profile:
    permission: TestPlugin.profile
    descrtion: Displays a players stats
  ping:
    permission: TestPlugin.ping
    description: Displays players ping

permissions:
  TestPlugin.game:
    description: Allows to join and leave games
    default: true
  TestPlugin.admin:
    description: Grants access to all administrative commands
    default: op
  TestPlugin.profile:
    description: Allows to check another players profile
    default: true
  TestPlugin.ping:
    description: Allows player to ping himself
    default: true